// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2619.SirLancebot2016;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.Solenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveTrainLeftFrontMotor;
    public static WPI_TalonSRX driveTrainLeftRearMotor;
    public static WPI_TalonSRX driveTrainRightFrontMotor;
    public static WPI_TalonSRX driveTrainRightRearMotor;
    public static Solenoid gearShiftshifter;
    public static Solenoid plungerbopper;
    public static WPI_TalonSRX shooterMotorsleftShooterMotor;
    public static WPI_TalonSRX shooterMotorsrightShooterMotor;
    public static WPI_TalonSRX collectorfeedRoller;
    public static WPI_TalonSRX collectorcenterRoller;
    public static DoubleSolenoid armsarmLift;
    public static Solenoid wristwristJoint;
    public static DoubleSolenoid shooterPivotshooterLift;
    public static DigitalInput ballSensorballSensorIO;
    public static Relay ballSensorballSensorSpike;
    public static Relay visionLightsvisionSpike;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static final int TIMEOUT_MS = 100;

	public static void init() {
		
        driveTrainLeftFrontMotor = new WPI_TalonSRX(11);
        LiveWindow.addActuator("DriveTrain", "LeftFrontMotor", driveTrainLeftFrontMotor);
        
        driveTrainLeftRearMotor = new WPI_TalonSRX(10);
        LiveWindow.addActuator("DriveTrain", "LeftRearMotor", driveTrainLeftRearMotor);
        
        driveTrainRightFrontMotor = new WPI_TalonSRX(2);
        LiveWindow.addActuator("DriveTrain", "RightFrontMotor", driveTrainRightFrontMotor);
        
        driveTrainRightRearMotor = new WPI_TalonSRX(3);
        LiveWindow.addActuator("DriveTrain", "RightRearMotor", driveTrainRightRearMotor);
        
        gearShiftshifter = new Solenoid(0, 6);
        LiveWindow.addActuator("GearShift", "shifter", gearShiftshifter);
        
        plungerbopper = new Solenoid(0, 4);
        LiveWindow.addActuator("Plunger", "bopper", plungerbopper);
        
        shooterMotorsleftShooterMotor = new WPI_TalonSRX(9);
        LiveWindow.addActuator("ShooterMotors", "leftShooterMotor", shooterMotorsleftShooterMotor);
        
        shooterMotorsrightShooterMotor = new WPI_TalonSRX(4);
        LiveWindow.addActuator("ShooterMotors", "rightShooterMotor", shooterMotorsrightShooterMotor);
        
        collectorfeedRoller = new WPI_TalonSRX(8);
        LiveWindow.addActuator("Collector", "feedRoller", collectorfeedRoller);
        
        collectorcenterRoller = new WPI_TalonSRX(5);
        LiveWindow.addActuator("Collector", "centerRoller", collectorcenterRoller);
        
        armsarmLift = new DoubleSolenoid(0, 2, 3);
        LiveWindow.addActuator("Arms", "armLift", armsarmLift);
        
        wristwristJoint = new Solenoid(0, 5);
        LiveWindow.addActuator("Wrist", "wristJoint", wristwristJoint);
        
        shooterPivotshooterLift = new DoubleSolenoid(0, 0, 1);
        LiveWindow.addActuator("ShooterPivot", "shooterLift", shooterPivotshooterLift);
        
        ballSensorballSensorIO = new DigitalInput(1);
        LiveWindow.addSensor("BallSensor", "ballSensorIO", ballSensorballSensorIO);
        
        ballSensorballSensorSpike = new Relay(0);
        LiveWindow.addActuator("BallSensor", "ballSensorSpike", ballSensorballSensorSpike);
        
        visionLightsvisionSpike = new Relay(2);
        LiveWindow.addActuator("VisionLights", "visionSpike", visionLightsvisionSpike);
        

  

		driveTrainLeftFrontMotor.set(0);
		driveTrainLeftRearMotor.set(0);

		driveTrainRightFrontMotor.set(0);
		driveTrainRightRearMotor.set(0);

		

		// Invert motors
		// THESE ARE FOR PLYBOT
		driveTrainRightFrontMotor.setInverted(true);
		driveTrainRightRearMotor.setInverted(true);

	}
}
